spring.datasource.url=jdbc:mysql://localhost:3306/ems_db
spring.datasource.username=root
spring.datasource.password=system@2715

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081